services:
  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025" # Mailpit Ui
      - "1025:1025" # SMTP
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: happynachbar
    ports:
      - "5433:5432" # nur für Zugriff vom Host
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d happynachbar"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    init: true
    build:
      context: ./api
    ports:
      - "4000:4000"
    environment:
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_REQUIRE_TLS: ${SMTP_REQUIRE_TLS}
      SMTP_TLS_REJECT_UNAUTH: ${SMTP_TLS_REJECT_UNAUTH}
      SMTP_TLS_SERVERNAME: ${SMTP_TLS_SERVERNAME}
      MAIL_FROM: ${MAIL_FROM}
      WEB_URL: ${WEB_URL}
      API_PORT: ${API_PORT}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      AWS_REGION: ${AWS_REGION}
      S3_BUCKET: ${S3_BUCKET}
      CLOUDFRONT_BASE_URL: ${CLOUDFRONT_BASE_URL}
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "-c", "npx prisma migrate deploy && node dist/src/main"]

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: happynachbar-web
    depends_on:
      - api
    environment:
      NODE_ENV: production
      API_URL: http://api:4000

    ports:
      - "3000:3000"

volumes:
  db_data:
